//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Perfume Perfume { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
