//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfume()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string PerfumeName { get; set; }
        public string ArticulNumber { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string PhotoName { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PerfumeType PerfumeType { get; set; }
    }
}
